### ISSUE TITLE
cyclonedds v0.10.x compatibility

### ISSUE THREAD

**Issue by Splinter1984** [atolab/cdds-util#5]
Hi. 
What is the current state of the project, is it supposed to switch to a new version of CycloneDDS?

**Comment by JEnoch** [comment]
Hi @Splinter1984,

This repo was an experiment that was largely rewritten in [kydos/cyclocut](https://github.com/kydos/cyclocut).
We are rather maintaining this **cyclocut** which is used in [eclipse-zenoh/zenoh-plugin-dds](https://github.com/eclipse-zenoh/zenoh-plugin-dds) (via [kydos/cyclors](https://github.com/kydos/cyclors)).
It didn't not yet switch to latest CycloneDDS, but that's part of the plan in eclipse-zenoh/zenoh-plugin-dds#51. We just didn't had time/resources for it yet.

Are you using directly **cdds-util** or was your question related to eclipse-zenoh/zenoh-plugin-dds ?

**Comment by Splinter1984** [comment]
Thanks for the answer. I assumed that the transition to a new version of cyclonedds in zenoh-plugin-dds is related to this repository

**Comment by JEnoch** [comment]
OK, thanks. I clarify this creating the new issue kydos/cyclocut#3 and archiving this repo.
